### ISSUE TITLE
Small field showing GNUPG Data and error in Python

### ISSUE THREAD

**Issue by dcialdella** [dcialdella/verysecurechat#18]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/cialdeld/Downloads/git/verysecurechat/client.v.1.py", line 115, in <lambda>
    tkMessage.bind("<Return>", (lambda event: getChatMessage(tkMessage.get("1.0", tk.END))))
  File "/home/cialdeld/Downloads/git/verysecurechat/client.v.1.py", line 222, in getChatMessage
    send_msg_to_server( msg )
  File "/home/cialdeld/Downloads/git/verysecurechat/client.v.1.py", line 246, in send_msg_to_server
    destIdx = tkUserList.curselection()[0] - 1
IndexError: tuple index out of range

**Comment by dcialdella** [comment]
the error appear when select <TODOS> and try tosend a message.

**Comment by dcialdella** [comment]
When select TODOS

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/cialdeld/Downloads/git/verysecurechat/client.v.1.py", line 115, in <lambda>
    tkMessage.bind("<Return>", (lambda event: getChatMessage(tkMessage.get("1.0", tk.END))))
  File "/home/cialdeld/Downloads/git/verysecurechat/client.v.1.py", line 222, in getChatMessage
    send_msg_to_server( msg )
  File "/home/cialdeld/Downloads/git/verysecurechat/client.v.1.py", line 246, in send_msg_to_server
    destIdx = tkUserList.curselection()[0] - 1
IndexError: tuple index out of range
